---
title: "Questão 10"
output:
  pdf_document:
    fig_crop: no
fontsize: 10pt
sansfont: Times
documentclass: article
geometry: 
 - a4paper
 - textwidth=18cm
 - textheight=21cm
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage[brazil, english, portuguese]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage[fixlanguage]{babelbib}
  - \usepackage{times}

  - \usepackage{graphicx}
  - \usepackage{wrapfig}
  - \usepackage{pdfpages}
  
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage{amsmath}
  
  - \usepackage{fancyhdr}
  - \usepackage{subcaption}
  - \usepackage{booktabs}
  - \usepackage{caption}
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  warning = FALSE,
  tidy.opts = list(width.cutoff = 60),
  tidy = TRUE,
  digits=3
  )
options(
  OutDec = ",", 
  knitr.table.format = "latex", 
  xtable.comment = FALSE
  )
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r}
library(tidyverse)
library(magrittr)
library(gridExtra)
library(corrplot)
library(ggfortify)
library(broom)
library(kableExtra)
source("../diag_norm.R")
source("../envel_norm.R")
source("../norm_diag.R")
source("../anainflu_norm.R")
source("../cook_hat.R")
source("../estimate_table.R")
source("../model_measures.R")
library(knitr)
```

##INSTALL PACKAGES
```{r}
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("nlme")
install.packages("EnvStats")
install.packages("plotrix")
install.packages("plyr")
install.packages("car")
```

##LIBRARIES
```{r}
library(tidyverse)
library(nlme)
library(ggplot2)
library(EnvStats)
library(plotrix)
library(car)
library(plyr)
library(xtable)
```

####LISTA 04

##09 - COELHOS
```{r}
##importando o banco de dados
coelhos <- read.table("https://www.ime.unicamp.br/~cnaber/Ratkowsky.dat", header = F)
names(coelhos) <- c("idade", "peso")
```

```{r}
##grafico de pontos inicial
ggplot(coelhos, aes(idade,peso)) + geom_point() + ggtitle("Gráfico de Dispersão") + xlab("Idade do coelho") + ylab("Peso da lente ocular seca")+ theme_linedraw()
```
##FUNCAO DO MODELO
```{r}
##Michaelis menten plot and equation
mm=function(conc,vmax,k) vmax*conc/(k+conc)
```

##AJUSTANDO O MODELO
```{r}
modelo <- nls(peso ~ mm(idade,a,b), data = coelhos, start = list(a = 250, b = 0.05))
summary(modelo)
```

```{r}
##grafico modelo
ggplot(coelhos, aes(idade,peso)) + geom_point() + geom_line(aes(y=predict(modelo) ),col = "red")+ ggtitle("Gráfico com o modelo ajustado", subtitle = "Modelo Não Linear") + xlab("Idade do coelho") + ylab("Peso da lente ocular seca")+ theme_linedraw()
```

##ANALISE RESIDUAL NLS()
```{r}
result3<-modelo
resid3 <- residuals(modelo,type="pearson")
a <- max(resid3)
b <- min(resid3)
par(mfrow=c(2,2))
plot(resid3,xlab="Índice", ylab="Resíduo Studentizado",
ylim=c(b-1,a+1), pch=16,cex=1.1,cex.axis=1.1,cex.lab=1.1)
abline(2,0,lty=2)
abline(-2,0,lty=2)
abline(0,0,lty=2)
#identify(tsi, n=1)
#title(sub="(c)")
#
plot(fitted(result3),resid3,xlab="Valores Ajustados", 
ylab="Resíduo Studentizado", ylim=c(b-1,a+1), pch=16,cex=1.1,cex.axis=1.1,cex.lab=1.1)
#
abline(2,0,lty=2)
abline(-2,0,lty=2)
abline(0,0,lty=2)
#boxplot(tsi,ylab="Res?duo Studentizado",cex=1.1,cex.axis=1.1,cex.lab=1.1)
hist(resid3,xlab="Resíduo Studentizado",ylab="Densidade",probability=TRUE,main="",cex=1.1,cex.axis=1.1,cex.lab=1.1)
#title(sub="(d)")
#identify(fitted(fit.model),tsi, n=1)
#
#qqnorm(resid3, pch = 1, frame = F)
qqPlot(resid3,"norm",mean=0,sd=1,col.lines=1,grid="FALSE",xlab="quantil da N(0,1)",ylab=paste("Quantil do resíduo normalizado"),cex=1.2,pch=19)
```


```{r}
##Gráfico Valor Predito x Valor Observado
ggplot(coelhos,aes(x = predict(modelo), y=peso)) + geom_point() + geom_abline(intercept = 0, slope = 1, col ="red") + ggtitle("Gráfico Valor Predito x Valor Observado", subtitle = "Modelo Não LInear") + xlab("Valor Predito") + ylab("Valor Observado")+ theme_linedraw()  
```












